### ISSUE TITLE
Progress of first scan has negative number

### ISSUE THREAD

**Issue by jeroensmeets** [MindblownHQ/wooping-shop-health#1]
First scan. Number of processed products went negative immediately after start, then slowly climbed up.

<img width="281" alt="shop-health-progress" src="https://github.com/user-attachments/assets/4ca5ac01-75ac-48d3-a3e9-6c658864f2a2">

**Comment by lucprincen** [comment]
Thanks for bringing this to our attention! 
Issue seems to be related to getting limited data out of Action Scheduler in `Controllers/Cron.php` (see line 113): 
![Scherm­afbeelding 2024-11-11 om 16 21 22](https://github.com/user-attachments/assets/7162b8f6-de5f-4326-9bb8-3fdf67d65f9a)
