### ISSUE TITLE
Clear current scan when a new one is triggered

### ISSUE THREAD

**Issue by mklasen** [MindblownHQ/wooping-shop-health#15]
It's currently possible to run multiple full scans simultaneously. This causes the progress bar [(introduced in 279)](https://github.com/MindblownHQ/shop-health/pull/279) to report a negative count and percentage. 

Relevant comment:
> The above indeed originates from when multiple scans are running. I think we have to solve this in a separate PR though, a new product scan should either:
> - Not be possible while another is running
> - Cancel all existing jobs and start again
> 
> Let's tackle this in a new issue

_Originally posted by @mklasen in https://github.com/MindblownHQ/shop-health/issues/279#issuecomment-2377045557_

I'm in favor of **clearing all current scans when a new scan is triggered.**

**Comment by lucprincen** [comment]
Related: #1
